# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: aws-eb-deploy
env:
  AWS_REGION:          eu-central-1
  EB_S3_BUCKET:        elasticbeanstalk-eu-central-1-725424636855
  EB_APP_NAME:         docker-react-ci
  EB_ENV_NAME:         DockerReactCi-dev-env
  DEPLOY_PACKAGE_NAME: actions_${{ github.sha }}.zip
  

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:        
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: build test image
        run: |
          docker --version
          docker build -t test-me -f Dockerfile.dev .
          
      - name: run tests
        run: |
          docker run -e CI=true test-me npm run test
          
  deploy:
    runs-on: [ubuntu-latest]
    needs: [test]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Create ZIP package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x .git*
        
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Copy depployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_S3_BUCKET }}/${{ env.EB_APP_NAME }}




